config/routes.rb
Rails.application.routes.draw do
  resources :welcome, only: [:index]

  devise_for :users, path_names: { sign_out:'sign_out' }

  resources :matchups do
    resources :opinions, only: [:new, :create, :destroy]
  end

  root to: "welcome#index"

  resources :characters, only: [:index, :show, :destroy]
end

app/models/character.rb
class Character < ActiveRecord::Base
  has_many :matchups

  validates :name,
    presence: true,
    uniqueness: true

  def self.search(query)
    where("name ilike ?", "%#{query}%")
  end
end

app/models/matchup.rb
class Matchup < ActiveRecord::Base
  has_many :opinions
  belongs_to :character
  belongs_to :opponent, class_name: "Character"

  validates :character, presence: true
  validates :opponent,
    presence: true,
    uniqueness: {
      scope: :character,
      message: "That matchup already exists!"
    }
  validate :no_duplicate_characters

  def tabulate
    char_count = 0
    opp_count = 0

    opinions.each do |opinion|
      if opinion.winner_id == character.id
        char_count += 1
      elsif opinion.winner_id == opponent.id
        opp_count += 1
      end
    end

    if char_count > opp_count
      "#{character.name} is winning by #{char_count - opp_count}."
    elsif opp_count > char_count
      "#{opponent.name} is winning by #{opp_count - char_count}."
    else
      'No Contest!'
    end
  end

  def no_duplicate_characters
    if character_id == opponent_id
      errors.add(:character_id, "Characters cannot battle themselves!")
    end
  end

  # def self.search(query)
  #   where("character_id like ?", "%#{query}%")
  # end
end

app/models/opinion.rb
class Opinion < ActiveRecord::Base
  belongs_to :matchup, counter_cache: true
  belongs_to :winner, class_name: "Character"
  belongs_to :user
  validates :body,
    presence: { message: "The opinion can't be empty!" },
    uniqueness: { message: "That opinion already exists!" }
  # validates :user, uniqueness: { scope: matchup } (also need uniqueness constraint on DB)
  validates :winner, presence: { message: "You must vote!" }
  validate :winner_in_matchup
  validates :user, uniqueness: { scope: :matchup }

  def winner_in_matchup
    if winner != matchup.character && winner != matchup.opponent
      errors.add(:winner_id, "Winner must be in matchup!")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :opinions

  mount_uploader :profile_photo, ProfilePhotoUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    role == "admin"
  end

  def has_opinion?(matchup)
    opinions.find_by(matchup_id: matchup.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:profile_photo, :first_name, :last_name]
  end

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_filter :authenticate_user!, except: [:index,:show]
  before_filter :authorize_user!, except: [:index, :new, :show, :create]

  def index
    if params[:search]
      @characters = Character.search(params[:search]).order("name ASC")
    else
      @characters = Character.order("name ASC").page(params[:page]).per(12)
    end
  end

  def show
    @character = Character.find(params[:id])
    @traits = JSON.parse(@character.body)
  end

  def destroy
    @character = Character.find(params[:id])
    @character.destroy
    redirect_to characters_path
  end

  def authorize_user
    unless user_signed_in? && current_user.admin?
      raise ActionController::RoutingError.new("Not Found")
    end
  end
end

app/controllers/matchups_controller.rb
class MatchupsController < ApplicationController
  before_filter :authenticate_user!, except: [:index,:show]
  before_filter :authorize_user!, except: [:index, :new, :show, :create]

  def index
    if params[:search]
      @matchups = Matchup.search(params[:search]).order('opinions_count desc')
    else
      @matchups = Matchup.order('opinions_count desc').page(params[:page]).per(10)
    end
  end

  def show
    @matchup = Matchup.find(params[:id])
    @opinion = Opinion.new
    @char_trait = JSON.parse(@matchup.character.body)
    @opp_trait = JSON.parse(@matchup.opponent.body)
  end

  def create
    @matchup = Matchup.new(matchup_params)
    if @matchup.save
      redirect_to matchups_path, notice: "The matchup has been created successfully."
    else
      flash[:notice] = "Your matchup could not be saved!"
      render "new"
    end
  end

  def new
    @matchup = Matchup.new
  end

  def destroy
    @matchup = Matchup.find(params[:id])
    @matchup.destroy
    redirect_to matchups_path
  end

  private

  def matchup_params
    params.require(:matchup).permit(:character_id, :opponent_id)
  end

  def authorize_user
    unless user_signed_in? && current_user.admin?
      raise ActionController::RoutingError.new("Not Found")
    end
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :authorize_user!, except: [:index, :new, :show, :create]

  def index
    @opinions = Opinion.all
  end

  def show
    @opinion = Opinion.find(params[:id])
  end

  def new
    @opinion = Opinion.new
    @char_trait = JSON.parse(@matchup.character.body)
    @opp_trait = JSON.parse(@matchup.opponent.body)
  end

  def create
    @opinion = Opinion.new(opinion_params)
    @matchup = Matchup.find(params[:matchup_id])
    @opinion.user = current_user
    @char_trait = JSON.parse(@matchup.character.body)
    @opp_trait = JSON.parse(@matchup.opponent.body)
    @opinion.matchup = @matchup
    @opinion.user_id = current_user.id

    if @opinion.save
      redirect_to matchup_path(@matchup), notice: "The opinion has been created successfully."
      UserMailer.welcome_email(current_user).deliver
    else
      render "matchups/show"
    end
  end

  private

  def opinion_params
    params.require(:opinion).permit(:body, :winner_id)
  end

  def authorize_user
    unless user_signed_in? && current_user.admin?
        raise ActionController::RoutingError.new("Not Found")
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout "welcome"

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/characters/index.html.erb
<h1>Character Choice</h1>

<ul class="small-block-grid-4">
  <% @characters.each do |character| %>
    <li><%= link_to character.name, character_path(character) %>   <img onerror="src='http://s3.amazonaws.com/char-fight-development/pokemon/pokeball.png'" src="http://s3.amazonaws.com/char-fight-development/pokemon/<%= character.name %>.png"></li>

    <% if current_user && current_user.admin? %>
      <%= link_to "Delete!", character_path(character), method: :delete %>
    <% end %>
  <%end%>
</ul>


<%= form_tag(characters_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search characters"%>
  <%= submit_tag "Search", :name => nil %>
<% end %>

<% if !params[:search] %>
  <br><%= paginate @characters %><br>
<br><% end %><br>

app/views/characters/show.html.erb
<body>
<h1 class = "title"><%= @character.name%></h1>
<img id = "pokemon" src = "http://s3.amazonaws.com/char-fight-development/pokemon/<%= @character.name %>.png" onerror="src='http://s3.amazonaws.com/char-fight-development/pokemon/pokeball.png'" alt = "Pokemon" height = "270" width = "270"/>
<table style = "width:220px">
  <tr>
    <td class = "odd"width = "70" id = "table-label">Type</td>
    <td class = "odd" width="150"><%= @traits["type"] %></td>
  </tr>
  <tr >
    <td id = "table-label" width = "70">Abilities</td>
    <td width="150"><%= @traits["abilities"] %> </td>
  </tr>
  <tr>
    <td class = "odd" width = "70" id = "table-label">Attack</td>
    <td  class = "odd" width="150"><%= @traits["attack"] %></td>
  </tr>
  <tr>
    <td  id = "table-label" width = "70">Defense</td>
    <td  width="150"><%= @traits["defense"] %></td>
  </tr>
  <tr>
    <td class= "odd" width = "70">Special Attack</td>
    <td class = "odd" width="150"><%= @traits["special_attack"] %></td>
  </tr>
  <tr>
    <td  id = "table-label" width = "70">Special Defense</td>
    <td  width="150"><%= @traits["special_defense"] %></td>
  </tr>
  <tr>
    <td class = "odd" width = "70">Speed</td>
    <td class = "odd" width="150"><%= @traits["speed"] %></td>
  </tr>
</table>
</div>

<h3><%= "#{@character.name} has battled:"%></h3>

<ul>
  <%if @character.matchups.length == 0 %>
    <li>No one yet</li>
  <%else %>
    <% @character.matchups.each do |matchup| %>
      <li><%= link_to matchup.opponent.name, matchup_path(matchup) %></li>
    <% end %>
  <% end %>
</ul>

<li><%=link_to "Go back to view all characters", characters_path%></li>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "CharBrawls!" %></title>

    <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Maven+Pro' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="clearfix">
      <% if current_user %>

        <li>
          <img src="http://fc03.deviantart.net/images2/i/2003/52/3/9/Pokeball_Opening.jpg"height="40" width="50" align = "left">
        </li>
      <% else %>
        <li>
          <img src="http://img3.wikia.nocookie.net/__cb20130901024704/clubpenguin/images/4/4c/Pokeball.png"height="40" width="40" align = "left">
        </li>
      <% end %>

      <li><%= link_to "Home", root_path%></li>
      <li><%= link_to "Characters", characters_path%></li>
      <li><%= link_to "Matchups", matchups_path%></li>

      <% if current_user %>
        <li><%=link_to "Create Matchup", new_matchup_path%></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Sign in", new_user_session_path%></li>
        <li><%= link_to "Sign up", new_user_registration_path%></li>
      <% end %>
    </nav>

    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <%if%>
      <p class="alert"><%= alert %></p>
    <%end%>

    <%= yield %>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body class="home">

    <%= yield %>

  </body>
</html>

app/views/matchups/index.html.erb
<h1>Current Matchups</h1>

<% @matchups.each do |matchup| %>
  <p>
    <img src="http://s3.amazonaws.com/char-fight-development/pokemon/<%= matchup.character.name %>.png" onerror="src='http://s3.amazonaws.com/char-fight-development/pokemon/pokeball.png'" width = "100px" height = "100px">
    <%= link_to "#{matchup.character.name} vs. #{matchup.opponent.name}", matchup_path(matchup) %><img src="http://s3.amazonaws.com/char-fight-development/pokemon/<%= matchup.opponent.name %>.png" onerror="src='http://s3.amazonaws.com/char-fight-development/pokemon/pokeball.png'" width = "100px" height = "100px">
  </p>

  <% if current_user && current_user.admin? %>
    <%= link_to "Delete!", matchup_path(matchup), method: :delete %>
  <% end %>
<% end %>

<%= paginate @matchups %>

app/views/matchups/new.html.erb
<h1><br>Matchup<br></h1>
<%= form_for @matchup do |f| %>

  <% if @matchup.errors.any? %>
    <p><%= "#{@matchup.errors.count} prevented your matchup from being saved:" %></p>
    <ul>
      <% @matchup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :character_id, "Character One" %>
  <%= f.collection_select :character_id, Character.all.order(:name), :id, :name, include_blank: true %>

  <%= f.label :opponent_id, "Character Two" %>
  <%= f.collection_select :opponent_id, Character.all.order(:name), :id, :name, include_blank: true %>

  <br><%= f.submit "Submit" %><br>

<% end %>

app/views/matchups/show.html.erb
</br>
<body>
<div class = "container">
  <div class = "stats">

    <h3 style = "text-align: center">
  <%= link_to "#{@matchup.character.name}", character_path(@matchup.character) %> vs. <%= link_to "#{@matchup.opponent.name}",character_path(@matchup.character) %>
    </h3>


    <div class = "competition">
      <h1 class = "title"><%= @matchup.character.name%></h1>
      <img id = "pokemon" onerror="src='http://s3.amazonaws.com/char-fight-development/pokemon/pokeball.png'" src="http://s3.amazonaws.com/char-fight-development/pokemon/<%= @matchup.character.name %>.png" alt = "Pokemon" height = "270" width = "270"/>

      </br>
      <table style = "width:220px">
        <tr>
          <td class = "odd" width = "70" id = "table-label">Type</td>
          <td class = "odd" width="150"><%= @char_trait["type"] %></td>
        </tr>
        <tr >
          <td id = "table-label" width = "70">Abilities</td>
          <td width="150"><%= @char_trait["abilities"] %> </td>
        </tr>
        <tr>
          <td class = "odd" width = "70" id = "table-label">Attack</td>
          <td  class = "odd" width="150"><%= @char_trait["attack"] %></td>
        </tr>
        <tr>
          <td  id = "table-label" width = "70">Defense</td>
          <td  width="150"><%= @char_trait["defense"] %></td>
        </tr>
        <tr>
          <td class= "odd" id = "table-label"width = "70">Special Attack</td>
          <td class = "odd" width="150"><%= @char_trait["special_attack"] %></td>
        </tr>
        <tr>
          <td  id = "table-label" width = "70">Special Defense</td>
          <td  width="150"><%= @char_trait["special_defense"] %></td>
        </tr>
        <tr>
          <td class = "odd" id = "table-label" width = "70">Speed</td>
          <td class = "odd" width="150"><%= @char_trait["speed"] %></td>
        </tr>
      </table>
    </div>

    <div class = "opponent">
      <h1 class = "title"><%= @matchup.opponent.name%></h1>
      <img id = "pokemon" onerror="src='http://s3.amazonaws.com/char-fight-development/pokemon/pokeball.png'" src ="http://s3.amazonaws.com/char-fight-development/pokemon/<%= @matchup.opponent.name %>.png" alt = "Pokemon" height = "270" width = "270"/>
      </br>
      <table style = "width:220px">
        <tr>
          <td class = "odd"width = "70" id = "table-label">Type</td>
          <td class = "odd" width="150"><%= @opp_trait["type"] %></td>
        </tr>
        <tr >
          <td id = "table-label" width = "70">Abilities</td>
          <td width="150"><%= @opp_trait["abilities"] %> </td>
        </tr>
        <tr>
          <td class = "odd" id = "table-label" width = "70" id = "table-label">Attack</td>
          <td  class = "odd" width="150"><%= @opp_trait["attack"] %></td>
        </tr>
        <tr>
          <td  id = "table-label" width = "70">Defense</td>
          <td  width="150"><%= @opp_trait["defense"] %></td>
        </tr>
        <tr>
          <td class= "odd" id = "table-label" width = "70">Special Attack</td>
          <td class = "odd" width="150"><%= @opp_trait["special_attack"] %></td>
        </tr>
        <tr>
          <td  id = "table-label" width = "70">Special Defense</td>
          <td  width="150"><%= @opp_trait["special_defense"] %></td>
        </tr>
        <tr>
          <td class = "odd" id = "table-label" width = "70">Speed</td>
          <td class = "odd"><%= @opp_trait["speed"] %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

<h1 style = "text-align: center"><%=@matchup.tabulate%></h1>

<ul>
<% @matchup.opinions.each do |opinion| %>
  <li class = "review"><% if opinion.user.profile_photo != nil%>
    <img id = "profile-photo" src = "<%= opinion.user.profile_photo %>" height = "50" width = "50">
  <%end%>
  <strong><%= opinion.user.first_name%> says:</strong><%= opinion.body %></li>
<% end %>



<% if current_user && !current_user.has_opinion?(@matchup)%>
  <%= form_for [@matchup, @opinion] do |f| %>
    <%= f.label :body, "Battle Notes" %>
    <%= f.text_field :body %>

    <%= f.label :vote, "Choose The Winner!" %>

    <%= radio_button(:opinion, :winner_id, @matchup.character.id) %><%= @matchup.character.name %>
    <%= radio_button(:opinion, :winner_id, @matchup.opponent.id) %><%= @matchup.opponent.name %>

    <br>

    <%= f.submit %>

    <% if @opinion.errors.full_messages.any? %>
      <% @opinion.errors.full_messages.each do |err| %>
        <%= err %>
        <br>
      <% end %>
    <% end %>
    <br>
  <% end %>
<%end%>


<%= link_to "Go Back", matchups_path %>
</body>

app/views/opinions/new.html.erb
<%= form_for new_matchup_opinion_path do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.check_box :vote, {}, 1, 0 %>
  <%= f.check_box :vote, {}, -1, 0 %>

  <%= f.submit %>

<% end %>

app/views/welcome/index.html.erb
<div class="writing">
  <h3><%= link_to "Click here to Enter Charbrawls", characters_path %></h3>
</div>